// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhZpbAMjaGV_2Y-GZfE47t5vtOXLI2XE',
    appId: '1:695303551022:web:8d27de0d6c332e427d47bf',
    messagingSenderId: '695303551022',
    projectId: 'nhomba-project-flutter',
    authDomain: 'nhomba-project-flutter.firebaseapp.com',
    storageBucket: 'nhomba-project-flutter.firebasestorage.app',
    measurementId: 'G-Q97P34NRYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KJ8833aVKz_0UuJQAlEUhFmNHFaI5pk',
    appId: '1:695303551022:android:d87be852b6e1250e7d47bf',
    messagingSenderId: '695303551022',
    projectId: 'nhomba-project-flutter',
    storageBucket: 'nhomba-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBektp4BvaN4fTHh_XmeJ7Luucii8PZc3k',
    appId: '1:695303551022:ios:232c646532eb26f27d47bf',
    messagingSenderId: '695303551022',
    projectId: 'nhomba-project-flutter',
    storageBucket: 'nhomba-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.nhombaProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBektp4BvaN4fTHh_XmeJ7Luucii8PZc3k',
    appId: '1:695303551022:ios:232c646532eb26f27d47bf',
    messagingSenderId: '695303551022',
    projectId: 'nhomba-project-flutter',
    storageBucket: 'nhomba-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.nhombaProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvhZpbAMjaGV_2Y-GZfE47t5vtOXLI2XE',
    appId: '1:695303551022:web:fa380119182a48bc7d47bf',
    messagingSenderId: '695303551022',
    projectId: 'nhomba-project-flutter',
    authDomain: 'nhomba-project-flutter.firebaseapp.com',
    storageBucket: 'nhomba-project-flutter.firebasestorage.app',
    measurementId: 'G-TCLWWSNRV3',
  );
}
